import Head from 'next/head';
import { useEffect, useState } from 'react';
import Board from './components/Board/Board';
const emojiList = [...'💣🧤🎩🌮🎱🌶🍕🦖'];

export default function Home() {
	const [
		shuffledMemoBlocks,
		setShuffledMemoBlocks,
	] = useState([]);
	const [
		selectedMemoBlock,
		setselectedMemoBlock,
	] = useState(null);
	const [animating, setAnimating] =
		useState(false);

	useEffect(() => {
		const shuffledEmojiList = shuffleArray([
			...emojiList,
			...emojiList,
		]);
		setShuffledMemoBlocks(
			shuffledEmojiList.map((emoji, i) => ({
				index: i,
				emoji,
				flipped: false,
			}))
		);
	}, []);

	const shuffleArray = (a) => {
		for (let i = a.length - 1; i > 0; i--) {
			const j = Math.floor(
				Math.random() * (i + 1)
			);
			[a[i], a[j]] = [a[j], a[i]];
		}
		return a;
	};

	const handleMemoClick = (memoBlock) => {
		const flippedMemoBlock = {
			...memoBlock,
			flipped: true,
		};
		let shuffledMemoBlocksCopy = [
			...shuffledMemoBlocks,
		];
		shuffledMemoBlocksCopy.splice(
			memoBlock.index,
			1,
			flippedMemoBlock
		);
		setShuffledMemoBlocks(
			shuffledMemoBlocksCopy
		);
		if (selectedMemoBlock === null) {
			setselectedMemoBlock(memoBlock);
		} else if (
			selectedMemoBlock.emoji ===
			memoBlock.emoji
		) {
			setselectedMemoBlock(null);
		} else {
			setAnimating(true);
			setTimeout(() => {
				shuffledMemoBlocksCopy.splice(
					memoBlock.index,
					1,
					memoBlock
				);
				shuffledMemoBlocksCopy.splice(
					selectedMemoBlock.index,
					1,
					selectedMemoBlock
				);
				setShuffledMemoBlocks(
					shuffledMemoBlocksCopy
				);
				setselectedMemoBlock(null);
				setAnimating(false);
			}, 1000);
		}
	};

	return (
		<>
			<Head>
				<title>Lopera Memo Game</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1 className='titulo'>
				JUEGO SIMPLE DE MEMORIA:
			</h1>
			<Board
				memoBlocks={shuffledMemoBlocks}
				animating={animating}
				handleMemoClick={handleMemoClick}
			/>
			<h1>
				Toca las tarjetas para voltearlas.
			</h1>
		</>
	);
}
